FROM python:3.9-alpine

RUN apk update && apk upgrade && apk add postgresql-dev gcc musl-dev

WORKDIR /src

COPY requirements.txt requirements-clock.txt ./
RUN pip install -r requirements.txt -r requirements-clock.txt

COPY src .

CMD python -m clock